(part "AHE300G-PA4-B"
    (packageRef "AHE300GPA4B")
    (interface
        (port "1" (symbPinId 1) (portName "INPUT(+-)") (portType INOUT))
        (port "2" (symbPinId 2) (portName "OUTPUT(+-)") (portType INOUT))
        (port "3" (symbPinId 3) (portName "INPUT(-+)") (portType INOUT))
        (port "4" (symbPinId 4) (portName "OUTPUT(-+)") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "AHE300G-PA4-B")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Hall Element SIP-4MA BULK 0.5K")
    (property "Datasheet_Link" "https://www.diodes.com/datasheet/download/AHE300.pdf")
    (property "symbolName1" "AHE300G-PA4-B")
)
